version: '3.7'
x-LOG_LEVEL         : &LOG_LEVEL LOG_LEVEL=info
x-NODE_ENV          : &NODE_ENV NODE_ENV=production
x-PREFIX            : &PREFIX PREFIX=
x-DATABASE_URL      : &DATABASE_URL DATABASE_URL=mongodb://wwwmongo:27017
x-DATABASE_USERNAME : &DATABASE_USERNAME DATABASE_USERNAME=admin
x-DATABASE_PASSWORD : &DATABASE_PASSWORD DATABASE_PASSWORD=admin
services:
  # FRONTEND VUE JS + NGINX
  www:
    build:
      context: ./    
      dockerfile: Dockerfile_frontend
    container_name: "www" 
    image: ucipass/www
    volumes: 
      - /home/aarato/github/www/frontend/dist:/usr/share/nginx/html
    ports: 
      - 8080:80    
    depends_on: 
      - wwwap 
  # BACKEND NODE JS APP    
  wwwap:
    build:
      context: ./    
      dockerfile: Dockerfile_backend
    container_name: "wwwap" 
    image: ucipass/wwwap
    environment: 
      - *LOG_LEVEL
      - *NODE_ENV
      - *PREFIX
      - *DATABASE_URL
      - *DATABASE_USERNAME
      - *DATABASE_PASSWORD
    command: node index.js
    ports: 
      - 3000:3000
    links: 
      - wwwmongo 
    depends_on: 
      - wwwmongo
  # MONGODB BACKEND DATABASE
  wwwmongo: 
    container_name: "wwwmongo" 
    image: mongo:latest 
    volumes: 
      - /tmp/db:/data/db 
    ports: 
      - 27017:27017 
    command: --logpath /dev/null
    # restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin 
      - MONGO_INITDB_ROOT_PASSWORD=admin
