FROM node:12.16.0-alpine as frontend-stage
WORKDIR /source/rp
COPY ./frontend/package.json  .
RUN npm install
COPY ./frontend/public  public
COPY ./frontend/src  src
COPY ./frontend/vue.config.js  .
COPY ./frontend/babel.config.js  .
RUN npm run build


FROM nginx:latest
WORKDIR /source/rp
COPY ./frontend/nginx.conf  /etc/nginx/conf.d/default.conf
COPY --from=frontend-stage /source/rp/dist /usr/share/nginx/html
