on: push
name: npm build and publish
jobs:
  build-and-publish:
    name: build and publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Docker Login
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Docker Build & Publish
      run: |
        docker build -f Dockerfile -t ucipass/openconnect .
        docker push ucipass/openconnect
